# test_mt19937.jl -- bit-exact reference vectors for the std::mt19937 / libc++ port.
# Every list in a vector file is drawn from a FRESH std::mt19937(seed) with a fresh
# distribution object.  Doubles are compared with == (bit-exact); on a mismatch the xor of
# the bit patterns is logged so a 1-ulp drift is visible.
#
# Primary: data/corpus/mt19937_vectors.json (frozen by the C++ before its removal; doubles as
# %.17g strings under *_str).  Fallback: mt19937_vectors_local.json (generated by
# scratchpad gen_mt.cpp with the same clang/libc++ 180100; doubles as "0x<hex>" bit patterns).
include("helpers.jl")
import JSON

const MT_SHARED = joinpath(CORPUS, "mt19937_vectors.json")
const MT_LOCAL = joinpath(CORPUS, "mt19937_vectors_local.json")

parse_f64(s::AbstractString) = startswith(s, "0x") ? reinterpret(Float64, parse(UInt64, s)) : parse(Float64, s)
parse_f64(x::Real) = Float64(x)

# @test got == want, logging the bit difference on failure
macro bitexact(got, want, label)
    quote
        g = $(esc(got)); w = $(esc(want))
        @test g == w
        g == w || @info $(esc(label)) g w xor = reinterpret(UInt64, g) ⊻ reinterpret(UInt64, w)
    end
end

function check_stream(seed, want, draw, label)
    rng = Kirigami.MT19937(seed)
    for w in want
        @bitexact draw(rng) parse_f64(w) label
    end
end

@testset "mt19937 textbook value" begin
    rng = Kirigami.MT19937()                     # default seed 5489
    for _ in 1:9999
        Kirigami.next_u32(rng)
    end
    @test Kirigami.next_u32(rng) == 4123659995
    @test Kirigami.next_u32(Kirigami.MT19937(5489)) == Kirigami.next_u32(Kirigami.MT19937())
end

@testset "mt19937 shared vectors" begin
    @test isfile(MT_SHARED)
    isfile(MT_SHARED) || return
    V = JSON.parsefile(MT_SHARED)
    @test V["_LIBCPP_VERSION"] == 180100
    for S in V["seeds"]
        seed = S["seed"]
        @testset "seed $seed" begin
            rng = Kirigami.MT19937(seed)
            @test [Kirigami.next_u32(rng) for _ in S["raw_u32"]] == UInt32.(S["raw_u32"])

            check_stream(seed, S["uniform_real_0_1_str"], r -> Kirigami.uniform_real(r, 0.0, 1.0), "uniform_real(0,1)")
            check_stream(seed, S["uniform_real_0_2pi_str"], r -> Kirigami.uniform_real(r, 0.0, 2pi), "uniform_real(0,2pi)")
            check_stream(seed, S["uniform_real_0_40_str"], r -> Kirigami.uniform_real(r, 0.0, 40.0), "uniform_real(0,40)")
            # the JSON-number copies must agree with the %.17g strings (sanity of the file itself)
            @test parse_f64.(S["uniform_real_0_1_str"]) == Float64.(S["uniform_real_0_1"])

            for (key, a, b) in (("uniform_int_0_1", 0, 1), ("uniform_int_0_99", 0, 99))
                rng = Kirigami.MT19937(seed)
                @test [Kirigami.uniform_int(rng, a, b) for _ in S[key]] == Int.(S[key])
            end

            rng = Kirigami.MT19937(seed)
            v = collect(0:19)
            Kirigami.shuffle!(v, rng)
            @test v == Int.(S["shuffle_0_19"])

            d = Kirigami.NormalDist(0.0, 1.0)
            check_stream(seed, S["normal_0_1_str"], r -> Kirigami.normal(d, r), "normal(0,1)")
        end
    end
end

@testset "mt19937 local vectors" begin
    @test isfile(MT_LOCAL)
    isfile(MT_LOCAL) || return
    V = JSON.parsefile(MT_LOCAL)
    @test V["textbook_10000th"] == 4123659995
    for S in V["seeds"]
        seed = S["seed"]
        @testset "seed $seed" begin
            rng = Kirigami.MT19937(seed)
            @test [Kirigami.next_u32(rng) for _ in S["u32"]] == UInt32.(S["u32"])
            check_stream(seed, S["canonical"], Kirigami.generate_canonical53, "generate_canonical")
            for key in ("uniform_real", "uniform_real2")
                U = S[key]
                check_stream(seed, U["values"], r -> Kirigami.uniform_real(r, U["a"], U["b"]), key)
            end
            for D in S["uniform_int"]       # ranges 0..6, 0..7, 0..99, -3..3, 5..5, 0..10^6
                rng = Kirigami.MT19937(seed)
                @test [Kirigami.uniform_int(rng, D["a"], D["b"]) for _ in D["values"]] == Int.(D["values"])
            end
            sh = S["shuffle"]
            rng = Kirigami.MT19937(seed)
            v = collect(0:sh["n"]-1)
            Kirigami.shuffle!(v, rng)
            @test v == Int.(sh["perm"])
            # the engine must have consumed exactly as many draws as libc++ did
            @test Kirigami.next_u32(rng) == UInt32(sh["next_u32"])
        end
    end
end

@testset "mt19937 edge cases" begin
    rng = Kirigami.MT19937(1)
    @test Kirigami.uniform_int(rng, 5, 5) == 5                  # rp == 1: no draw consumed
    @test Kirigami.next_u32(rng) == Kirigami.next_u32(Kirigami.MT19937(1))
    @test_throws ArgumentError Kirigami.uniform_int(rng, 3, 2)
    rng = Kirigami.MT19937(2)
    for _ in 1:1000
        @test -3 <= Kirigami.uniform_int(rng, -3, 3) <= 3
        @test 0.0 <= Kirigami.generate_canonical53(rng) <= 1.0
    end
    @test Kirigami.shuffle!([1], rng) == [1]
    @test Kirigami.shuffle!(Int[], rng) == Int[]
    v = collect(1:50)
    Kirigami.shuffle!(v, rng)
    @test sort(v) == collect(1:50)
    # normal: the cached second variate is returned without touching the engine
    d = Kirigami.NormalDist(0.0, 1.0)
    Kirigami.normal(d, rng)
    before = Kirigami.next_u32(deepcopy(rng))
    Kirigami.normal(d, rng)
    @test Kirigami.next_u32(rng) == before
end
